name: Pull Request Checks

on:
  pull_request:
    branches:
      - main

jobs:
  checks:
    name: Run Checks
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Type check
        run: bun run check-types

      - name: Build web application
        run: |
          cd apps/web
          bun run build

      - name: Build server (dry run)
        run: |
          cd apps/server
          bun run build